<style type="text/css">
.activitediv
{
	float:left;
	overflow:hidden;
	height:130px;
	width:495px;
	padding:0px;
	margin:0px;
	margin-bottom:20px;
	margin-left:0px;
}
#lien_des_activites a
{	
float:left;
	dispay:block;
	position:relative;
	bottom:0px;
	left:0px;
	margin:0px;
	padding:0px;
	margin-left:20px;
	margin-bottom:20px;
	text-decoration:none;
} 
.contenu_du_lien
{
	background-color:#ffffcc;
	overflow:hidden; 
	margin:0px;
	padding:0px;
	border:1px solid black;
	color:black;
	height:130px;
	width:475px;
}
.contenu_du_lien:hover
{
	background-color:white;
	cursor:pointer;
}
.contenu_du_lien:hover img
{
	background-color:white;
	cursor:auto;
}
.contenu_du_lien img
{
	border-style:none;
	float:left;
	padding:0px;
	margin:5px;
	margin-top:5px;
	margin-bottom:5px; 
}
.description_du_lien
{ 
	float:right;
	width:298px;
	height:118px;
	margin:0px;
	margin-top:5px;
	margin-right:5px;
	padding:0px;
	border:1px solid black;
	background-color:#dce1e2;
	vertical-align:top;
	overflow:hidden;
	background-image:url("image/Frame_du_CMS/description1.jpg");
	background-repeat:repeat-x;
}
.contenu_du_lien:hover .description_du_lien 
{
	background-color:red;
	background-image:url("image/Frame_du_CMS/description2.jpg");
	background-repeat:repeat-x;
	overflow:auto;
}
.description_du_lien p
{
	margin:0px;
	margin-top:7px;
	padding:0px;
	padding-left:6px;
	color:gray;
}
.titre
{
	background-image:url("image/Frame_du_CMS/titre.jpg");
	background-repeat:repeat-x;
	height:23px;
	position:relative;
	top:0px;
	float:left;
	margin:0px;
	margin-right:10px;
	padding:0px; 
	padding-left:5px;
	padding-right:5px;
	padding-bottom:3px;
	color:#cc3200; 
	font-size:20px
}
.contenu_du_lien:hover .titre
{
	color:white;
}
#topic_center
{
	width:100%;
	overflow:auto;
}
#h1rouge
{
	margin-top:0px;
	padding-top:0px;
	text-align:center;
	font-size:70px;
	color:#b03736;
}
#h1noir
{
	margin-top:0px;
	padding-top:0px;
	text-align:center;
}
#non_centre
{
	margin-top:0px;
	padding-top:0px;
}
</style>